# Generated by Django 4.2.18 on 2025-01-29 20:29

from django.db import migrations, models
import skate_spots.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('type', models.CharField(choices=[('skatepark', 'Pista'), ('skateshop', 'Loja'), ('event', 'Evento')], max_length=10, verbose_name='Tipo')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('lighting', models.BooleanField(verbose_name='Iluminacao Disponível?')),
                ('water', models.BooleanField(verbose_name='Água Disponível?')),
                ('bathroom', models.BooleanField(verbose_name='Banheiro Disponível?')),
                ('create_date', models.DateTimeField(verbose_name='Data de Criação')),
                ('zip_code', models.CharField(max_length=9, validators=[skate_spots.models.validar_cep], verbose_name='CEP')),
                ('street', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=30, verbose_name='Número')),
                ('district', models.CharField(max_length=60, verbose_name='Bairro')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('state', models.CharField(max_length=30, verbose_name='Estado')),
                ('country', models.CharField(max_length=30, verbose_name='País')),
            ],
        ),
    ]
