# Generated by Django 4.2.18 on 2025-01-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='local',
            name='latitude',
            field=models.FloatField(default=1, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='local',
            name='longitude',
            field=models.FloatField(default=1, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
