# Generated by Django 4.2.18 on 2025-06-02 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0002_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localimage',
            name='skateevent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skate_spots.skateevent'),
        ),
        migrations.AlterField(
            model_name='localimage',
            name='skateshop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skate_spots.skateshop'),
        ),
        migrations.AlterField(
            model_name='localimage',
            name='skatespot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skate_spots.skatespot'),
        ),
    ]
