# Generated by Django 4.2.18 on 2025-01-31 02:01

from django.db import migrations, models
import django.db.models.deletion
import skate_spots.models


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0002_local_latitude_local_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=9, validators=[skate_spots.models.validar_cep], verbose_name='CEP')),
                ('street', models.CharField(max_length=250, verbose_name='Logradouro')),
                ('number', models.CharField(max_length=30, verbose_name='Número')),
                ('district', models.CharField(max_length=60, verbose_name='Bairro')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('state', models.CharField(max_length=30, verbose_name='Estado')),
                ('country', models.CharField(max_length=30, verbose_name='País')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
            ],
        ),
        migrations.CreateModel(
            name='SkateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skate_spots.location')),
            ],
        ),
        migrations.CreateModel(
            name='SkateShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skate_spots.location')),
            ],
        ),
        migrations.CreateModel(
            name='SkateSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('lighting', models.BooleanField(verbose_name='Iluminacao Disponível?')),
                ('water', models.BooleanField(verbose_name='Água Disponível?')),
                ('bathroom', models.BooleanField(verbose_name='Banheiro Disponível?')),
                ('create_date', models.DateTimeField(verbose_name='Data de Criação')),
                ('location_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skate_spots.location')),
            ],
        ),
        migrations.DeleteModel(
            name='Local',
        ),
    ]
