# Generated by Django 4.2.18 on 2025-02-01 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0003_location_skateevent_skateshop_skatespot_delete_local'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Imagem')),
                ('main_image', models.BooleanField(default=False, verbose_name='Imagem Principal?')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('skateevent_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skateevent')),
                ('skatesphop_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skateshop')),
                ('skatespot_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skatespot')),
            ],
        ),
    ]
