# Generated by Django 4.2.18 on 2025-06-03 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0004_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='localimage',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
