# Generated by Django 4.2.18 on 2025-02-01 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0004_localimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localimage',
            name='skateevent_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skateevent'),
        ),
        migrations.AlterField(
            model_name='localimage',
            name='skatesphop_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skateshop'),
        ),
        migrations.AlterField(
            model_name='localimage',
            name='skatespot_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skatespot'),
        ),
    ]
