# Generated by Django 4.2.18 on 2025-02-01 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0005_alter_localimage_skateevent_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localimage',
            old_name='skatesphop_id',
            new_name='skateshop_id',
        ),
    ]
