# Generated by Django 4.2.18 on 2025-06-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0005_localimage_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='skatespot_id',
            field=models.ManyToManyField(blank=True, to='skate_spots.skatespot'),
        ),
    ]
