# Generated by Django 4.2.18 on 2025-02-01 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0006_rename_skatesphop_id_localimage_skateshop_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localimage',
            name='skateevent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skateevent'),
        ),
        migrations.AlterField(
            model_name='localimage',
            name='skateshop_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skateshop'),
        ),
        migrations.AlterField(
            model_name='localimage',
            name='skatespot_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skate_spots.skatespot'),
        ),
    ]
