# Generated by Django 4.2.18 on 2025-04-27 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0007_alter_localimage_skateevent_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
            ],
        ),
        migrations.AddField(
            model_name='skateevent',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='skateevent',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Encerramento'),
        ),
        migrations.AddField(
            model_name='skateevent',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Nome')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('modality_id', models.ManyToManyField(blank=True, to='skate_spots.modality')),
                ('skatespot_id', models.ManyToManyField(blank=True, to='skate_spots.skatespot')),
            ],
        ),
    ]
