# Generated by Django 4.2.18 on 2025-02-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0007_alter_localimage_skateevent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skateevent',
            name='create_date',
            field=models.DateTimeField(default='2025-02-01', verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skateevent',
            name='end_date',
            field=models.DateTimeField(default='2025-02-01', verbose_name='Data de Encerramento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skateevent',
            name='start_date',
            field=models.DateTimeField(default='2025-02-01', verbose_name='Data de Início'),
            preserve_default=False,
        ),
    ]
