# Generated by Django 4.2.18 on 2025-06-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0008_customuser_favorite_spots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modality',
            name='skatespot_id',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='modality_id',
        ),
        migrations.RemoveField(
            model_name='structure',
            name='skatespot_id',
        ),
        migrations.AddField(
            model_name='skateshop',
            name='business_hours',
            field=models.JSONField(blank=True, null=True, verbose_name='Horários de funcionamento'),
        ),
        migrations.AddField(
            model_name='skateshop',
            name='catalogo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='CATALOGOS/'),
        ),
        migrations.AddField(
            model_name='skateshop',
            name='website',
            field=models.URLField(blank=True, max_length=250, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='skateshop',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='skatespot',
            name='modalities',
            field=models.ManyToManyField(blank=True, to='skate_spots.modality'),
        ),
        migrations.AddField(
            model_name='skatespot',
            name='structures',
            field=models.ManyToManyField(blank=True, to='skate_spots.structure'),
        ),
    ]
