# Generated by Django 4.2.18 on 2025-05-20 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skate_spots', '0008_modality_skateevent_create_date_skateevent_end_date_and_more'),
        ('skate_spots', '0008_skateevent_create_date_skateevent_end_date_and_more'),
    ]

    operations = [
    ]
